[phases.setup]
# Add "ta-lib", Python, AND the "gcc" compiler package
nixPkgs = ["ta-lib", "python310", "gcc"]

# Optional: uncomment if you need extra system build tools
# aptPkgs = ["build-essential"] # Usually not needed when using nixPkgs for compiler

[start]
# Explicit start command using python3.10 explicitly for clarity
cmd = "python3.10 -m freqtrade trade --config user_data/config.json --strategy hype_strategy"